[package]
name = "sparse-bitpacker"
version = "0.1.0"
edition = "2021"

[dependencies]
bitpacking = { version = "0.9.2", default-features = false, features = ["bitpacker1x"] }

[dev-dependencies]
rand = "0.8"
proptest = "1"
